quiet: False
disable-version-string: True
with-expecter: True
mockname: "{{.InterfaceName}}"
filename: "{{.MockName}}.go"
outpkg: mocks
packages:
  github.com/vektra/mockery/v2/pkg: 
    interfaces:
      TypesPackage:
      RequesterVariadic:
        config: 
          with-expecter: False