env: "local"
storage_path: "./storage/storage.db"
jwt_app_secret: "test-secret"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "inf"
grpc_client:
  address: "localhost:44044"
  timeout: "5s"
  retries: 2